### ISSUE TITLE
Failed to Execute Filter Command

### ISSUE THREAD

**Issue by Ocamp09** [bioinfolabmu/GenericRepeatFinder#7]
I got the following error while compiling the grf:

sh: 1: ./grf-filter: not found
failed to execute command ./grf-filter 10 20 5 50 ./grf_data/perfect.fasta ./grf_data/perfect.fasta.filterd

Let us know if this will cause an error in our dataset or how we can prevent this. Thank you.

**Comment by sjm888888** [comment]
Looks like the grf-filter binary does not exist in the directory where you ran the shell script from. Can you double check if your have a file called "grf-filter" in the directory?
Another possibility is that if you use the pre-compiled binary (i.e., under GenericRepeatFinder/bin ) and it does not fit your system, the OS could also complain xxx not found. In this case, you have to follow the instructions in readme.txt (ses [1] Installation of GRF) to compile grf from source code. I think the pre-compiled binaries are x64 ELF.

**Comment by Ocamp09** [comment]
We downloaded using Anaconda as directed by Dr. Liang, however that did not seem to be working. I tried to install and compile on another remote linux server but it did not compile and threw the error sh ./grf-filter permission denied. I have no tried to install it on my macbook and it won't recognize grf-main. What operating systems are supported by the program? I am not sure how to solve these issues.

**Comment by sjm888888** [comment]
Can you show me the command you used to compile on the remote linux server? 
64-bit Linux should be supported.

**Comment by Ocamp09** [comment]
grf-main -i Homo_sapiens.GRCh38.dna.chromosome.1.valid.fa -o grf_results -c 0 
--min_tr 10 --max_tr 20 -s 5 -t 4 -f 0 --min_spacer_len 5 --max_spacer_len 50 --
max_mismatch 0 --seed_mismatch 0 --max_indel 0
We are just trying to get inverted repeats using grf-main.

**Comment by sjm888888** [comment]
It's a runtime error. Can you check if the file ./grf-filter is executable?

**Comment by Ocamp09** [comment]
It is showing that grf-filter is read and write only should I try to update permissions?

**Comment by sjm888888** [comment]
Yes, please change it to executable. 
chmod +x

**Comment by jsromanowski** [comment]
Hello,
I also seem to have a similar grf-filter issue. 

When I run the following command: (searching for tandem direct repeats)
$ grf-main -i AAEL005793_ebony_genomic.fas -o . -c 2 --min_spacer_len 1000 --max_spacer_len 20000 --min_tr 300

I receive the error: 
"sh: 1: ./grf-filter: not found
failed to execute command ./grf-filter 300 2147483647 1000 20000 ./perfect.fasta ./perfect.fasta.filterd"

Additionally, when I type: 
"$ grf-filter" 

I receive:
"This program filters inverted repeats/MITEs/direct repeats according to given spacer and terminal repeat (TR) lengths. Usage: grf-filter <min_TR_len> <max_TR_len> <min_spacer_len> <max_spacer_len> <input_fasta> <output>"

Any help is appreciated, thanks in advance.

**Comment by sjm888888** [comment]
Thanks for reporting this issue. I do find a issue in grf-main source code and will fix it later this week.
For a quick solution, you need to specify the path for grf-main when running it. E.g., 
~/grf.XXX/bin/grf-main -i AAEL005793_ebony_genomic.fas -o . -c 2 --min_spacer_len 1000 --max_spacer_len 20000 --min_tr 300

**Comment by sjm888888** [comment]
I have just pushed a fix. Can you pull the latest code from master and try to see if that fix your problem? If fixed, I will make a new release.

**Comment by jsromanowski** [comment]
Hello again,

I apologize for my delay in responding. I downloaded the most recent source
code version 1.0.1, then unzipped the .tar.gz file, changed to my grf-1.0.1
directory, used the 'make' command, and added the grf/bin directory to my
path. It seems I still receive the grf-filter 'not found' error. This error
is bypassed by your suggestion to specify the path to grf-main in my
command, however I am unable to run my command without using the direct
path for grf-main at the beginning.

For reference, this is the command I ran:

grf-main -i  AAEL005793_ebony_genomic.fas -o
AAEL005793_ebony_tr100_mins50_maxs1kb -c 2 --min_tr 100 --min_space 50
--max_spacer_len 1000 -t 16

This is the output I received:

start: Sun Jun 18 14:50:14 2023

calculate cumulative scores in chromosome AAEL005793_ebony_genomic: Sun Jun
18 14:50:14 2023

find repeats in chromosome AAEL005793_ebony_genomic: Sun Jun 18 14:50:14
2023

remove redundant sequences and print: Sun Jun 18 14:50:14 2023

sh: 1: /grf-filter: not found
failed to execute command /grf-filter 100 2147483647 0 1000
AAEL005793_ebony_tr100_mins50_maxs1kb/perfect.fasta
AAEL005793_ebony_tr100_mins50_maxs1kb/perfect.fasta.filterd

Best,

Joe

**Comment by sjm888888** [comment]
Hi Joe,
Thanks for trying out. I made another release to fix the bug (1.0.2). Please try that out.
I tried 1.0.2 on my machine and it worked well using similar command.

**Comment by jsromanowski** [comment]
Hi Jieming,

I have tried 1.0.2 version and the grf-filter seems to work with no error
messages on my end.

Bugs aside, I am using GRF to find repeats of near perfect identity and of
a certain size (roughly 1kb) and space apart (potentially up to 10 or
20kb). Ideally, I would also like to have these repeat 'hits' listed out to
me along with their genomic locations. I have been using the GRF terminal
direct repeat option (-c 2), however I have not had any luck with this
pursuit. It seems the interspersed repeat may also be an avenue worth
exploring, so I will give this a try, too.

My question for you is: am I on the right track with the programs within
GRF I have been attempting to use? Or is there another GRF option you would
recommend for this purpose?

Best,

Joe

**Comment by sjm888888** [comment]
Hi Joe,
Option -c 2 is the correct option to use.
I suggest you to try the following params:
--min_space 900 (since the size of repeated region is ~1k, the minimum distance between seed regions is ~990)
--max_spacer_len 20000

**Comment by jsromanowski** [comment]
Great. Thank you very much for the suggestion.

-Joe
